### PR TITLE
Added the animations

### PR DESCRIPTION
**Pull request by suraj-9849**
issue : #63 
I have added the animations to this website using the GSAP (A JS library) by installing 

1)npm i gsap

2)npm i @gsap/react

Also worked on scroll trigger like when ever the component is trigger then the animation starts working which was achieved by the IntersectionObserver

### CODE REVIEW

**Comment by suraj-9849** [comment]
https://github.com/omrajsharma/bigohhh.com/assets/146669517/04fd8c64-46e9-4508-9c0f-f1a369d73ace

@omrajsharma please help me sir I made all the best changes and while creating the PR Y it is showing this error can u please tell me so that I can rectify

**Comment by omrajsharma** [comment]
Hi Suraj 
Build is failing for this PR. please check

**Comment by omrajsharma** [comment]
Can't we make it without any library?

**Comment by suraj-9849** [comment]
no sir it is the GSAP library which has the best animation tools

**Comment by omrajsharma** [comment]
@suraj-9849 why can't we code it ?

**Comment by suraj-9849** [comment]
Yes we can but the best tools are provided by the GSAP library may I know why cant we use it. If you tell me then I will know about it right @omrajsharma

**Comment by omrajsharma** [comment]
@suraj-9849 library overwelms the project, provides less flexibility and controls over features, that's why we should avoid using libraries to get more flexibility and performance of our applications.

**Comment by omrajsharma** [comment]
@suraj-9849 any update ??

**Comment by suraj-9849** [comment]
@omrajsharma I cant implement the animations using those library sorry sir

**Pull request closed without merging**
