### PR TITLE
Create greetings.yaml

### PR DESCRIPTION
**Pull request by sanmarg**
Added For #61

### CODE REVIEW

**Comment by omrajsharma** [comment]
Hi @sanmarg 
I'm not very familiar to github action. Can you please help me understand how to proceed to the following PR.

**Comment by sanmarg** [comment]
Sure, the GitHub actions consist of workflows or you can say CI/CD pipeline-like thing. The workflows are stored in the directory "/.github/workflows/" and they run automatically when there is any trigger triggered to run the workflow.

So, how to proceed with this PR... you don't have to follow any complex tasks or something just like others just merge it and it will automatically run on each issue.

**Comment by sanmarg** [comment]
Could you please add the labels to it considering its technicalities.

**Comment by sanmarg** [comment]
Any updates? Please assign this PR to me.

**Pull request merged**
