### PR TITLE
404 page for application #9 [UPDATED]

### PR DESCRIPTION
**Pull request by nishant0708**
404 page for application #9 [UPDATED]

Added 404 ERROR page  According to new directory structure.
image

### CODE REVIEW

**Comment by muskandn** [comment]
Hello @nishant0708 
I am new to next js, after cloning the repo, when i m writing the command
next start or next build i m getting this
image
can u please help me with this... what to do further 
backend is running perfectly

**Comment by nishant0708** [comment]
See first run npm install
And then everything will work fine

**Comment by nishant0708** [comment]
And for pr part just create branch in your fork repository push your code
and then go to GitHub and raise new pull request..and that's it .. and if
you don't know commands you can use Google for it ..

**Comment by muskandn** [comment]
Actually I have done the npm install wala part after cloning then only backend is running but for fronted part I am getting this error. 
Have you done something else except cloning and running npm install before next build or next start?

**Comment by nishant0708** [comment]
No but make sure that on doing cd your path is ..\bigohhh.com\client

**Comment by muskandn** [comment]
> No but make sure that on doing cd your path is ..\bigohhh.com\client



> No but make sure that on doing cd your path is ..\bigohhh.com\client

Yeah path is also this only...

**Comment by nishant0708** [comment]
hey @omrajsharma please check....

**Comment by muskandn** [comment]
> No but make sure that on doing cd your path is ..\bigohhh.com\client

Hey @nishant0708 thank you for your coordination. 
The error has been solved. I don't know how there were some issue in my hidden files and it was asking for some MH directory. Removing n reinstalling node modules n explicitly installing next resolved the issue.

**Comment by omrajsharma** [comment]
Good work done @nishant0708 , I'm merging your PR.

**Pull request merged**
