### PR TITLE
Added the best animations 

### PR DESCRIPTION
**Pull request by suraj-9849**
issue : #25 
I have added the best animations to this website by using the GSAP animations library so I installed 

1) ```npm i gsap```
2)```npm i @gsap/react```

Worked on the intersectingObserver -> where when ever the component is triggered then the animation starts

### CODE REVIEW

**Comment by suraj-9849** [comment]
Help me @omrajsharma I want to integrate the animations how should I resolve those

**Comment by omrajsharma** [comment]
@suraj-9849 please resolve the conflicts.

**Comment by omrajsharma** [comment]
Hi
We've updated our folder structure, you need to take the latest pull from this project and then raise a new PR. Do let me know if you need any help.

**Comment by suraj-9849** [comment]
Yeah ok sir I will do it @omrajsharma

**Pull request closed without merging**
