### PR TITLE
Fixed Footer Navigation Links 

### LINKED ISSUE #65: Enhancement : Issue with Footer Navigation Links and Missing Contact Page
Dear @omrajsharma ,

I observed that the navigation links in the footer of your website are not functioning properly. Specifically, these links only navigate to the home section instead of their designated destinations.

Additionally, I noticed that there is a link to a contact page in the footer, but the contact page itself appears to be missing or inaccessible.

I have recorded a video demonstration of the issues to provide a clear understanding. You can view the video here:( Sorry for the video Quality )

https://github.com/omrajsharma/bigohhh.com/assets/145179532/f7fd49c5-abd0-4c87-8064-d36b84414d18

I'm interested in addressing these issues and enhancing the functionality of your website. Please consider assigning me this task, and I will provide my best effort to resolve these navigation and contact page issues.

Thank you for your attention to this matter.

### PR DESCRIPTION
**Pull request by Aniket-2504**
### What does this PR do?

This PR addresses issue #65  by fixing the navigation links in the footer.
 Fixes #65 

### Description

 I've fixed the navigation links to ensure they navigate to the correct sections on the single-page website. Regarding the missing contact page, 
I've refrained from adding it as the website doesn't have separate pages for routes, which could disrupt the user flow. If desired, I can create a new enhancement issue to discuss adding a contact page in a way that maintains the site's seamless navigation.

### Fixes

Changes Made:

1. Corrected footer navigation links to point to the appropriate sections.
2. Ensured consistent navigation experience throughout the website.

### Additional Notes:

I've tested the changes locally and verified that the footer navigation now functions correctly. If there are any further suggestions or adjustments needed, please let me know.

### Screenshots 

https://github.com/omrajsharma/bigohhh.com/assets/145179532/ed9c54dd-1c5e-4d39-8e09-e5173e2f4dce

### Checklist
- [x] I have read and followed the [Contribution Guidelines](https://github.com/omrajsharma/bigohhh.com/blob/main/Contribution.md).
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have tested these changes locally.

### CODE REVIEW

**Comment by omrajsharma** [comment]
Hi @Aniket-2504 
changes looks stunning. Can we also make scroll behavior to smooth ?

**Comment by Aniket-2504** [comment]
Thanks a lot @omrajsharma , yeah sure!  just give me some hours i'll be back with chnages.

**Comment by Aniket-2504** [comment]
hello @omrajsharma , It's done I added a smooth scrolling using the css property , Hope you like it

**Comment by Aniket-2504** [comment]
hello @omrajsharma, Is everything okay?

**Comment by omrajsharma** [comment]
Thank you, @Aniket-2504 ! The PR looks fantastic 🤩. I appreciate your contribution and have merged it. Please feel free to explore more issues in the issues section. I look forward to your valuable contributions in the future.

**Comment by Aniket-2504** [comment]
Thanks a lot @omrajsharma , appreciate you brother

**Pull request merged**
