### PR TITLE
Added Read me in the latest repo

### PR DESCRIPTION
**Pull request by m-tabish**
Do leave a comment if any change is to be made

### CODE REVIEW

**Comment by omrajsharma** [comment]
Hi @m-tabish can you please resolve the conflicts

**Comment by omrajsharma** [comment]
also please remove contributer.md from client

**Comment by omrajsharma** [comment]
no worries, I'm merging this PR

**Comment by omrajsharma** [comment]
#59 issue resolved

**Comment by omrajsharma** [comment]
#8 issue resolved*

**Comment by m-tabish** [comment]
Kindly check PR #60 also. Happy to work on this.

**Pull request merged**
