### PR TITLE
About page

### PR DESCRIPTION
**Pull request by dhruv8433**
### Description

About page #31

@omrajsharma 

created about page as you say
[Provide a brief overview of the changes introduced by this pull request.]

### Added
- added about page
- added news section in about
- added instructors section
- added company section
- added partners section
- added investors section

[Cite any related issues or bugs that this PR addresses, e.g., "Fixes #123"]
"Fixes #66 "

### Type of PR
- [x] Feature enhancement

### Screenshots (if applicable)
Screenshot 2024-05-14 at 16-39-48 BigOhhh - Code Your Dreams

[If your changes include UI updates, provide screenshots to illustrate the changes.]

### Additional Notes

[Include any additional information or context that might be helpful for reviewers.]

### Checklist
- [x] I have read and followed the [Contribution Guidelines](https://github.com/omrajsharma/bigohhh.com/blob/main/Contribution.md).
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, snapshots, and videos after making the changes.
- [x] I have not borrowed code without disclosing it, if applicable.
- [x] This pull request is not a Work In Progress (WIP), and only completed and tested changes are included.
- [x] I have tested these changes locally.

### CODE REVIEW

**Comment by dhruv8433** [comment]
@omrajsharma please check it and merge it

**Comment by dhruv8433** [comment]
@omrajsharma please check it and merge

**Comment by dhruv8433** [comment]
@omrajsharma 
sure, i will check the code.

**Comment by dhruv8433** [comment]
@omrajsharma  
can you please tell me excetly what error is that because i am unable to find error..
can you please provide me screen short of vercel deployment

**Comment by omrajsharma** [comment]
below is the error of the deployment

Screenshot 2024-05-19 at 1 19 32 PM

**Comment by dhruv8433** [comment]
Ok i will check...

**Comment by dhruv8433** [comment]
@omrajsharma please check this and merge it

**Comment by dhruv8433** [comment]
@omrajsharma 

check this out, i resolve all conflicts and errors

Screenshot 2024-05-14 at 16-39-48 BigOhhh - Code Your Dreams

**Comment by dhruv8433** [comment]
@omrajsharma  please response

**Comment by omrajsharma** [comment]
Screenshot 2024-05-22 at 1 17 02 AM
I'm getting error on about page. Can you please check this ?

**Comment by dhruv8433** [comment]
@omrajsharma Now you can check that and please merge it

**Comment by dhruv8433** [comment]
@omrajsharma  please check this and close #31 

i resolve all conflicts and errors 
please merge it

**Comment by dhruv8433** [comment]
@omrajsharma 

review it and merge it 
as you told me i completelly follow your recommandation for about UI ,why you dont give response and why not merged it

**Comment by dhruv8433** [comment]
@omrajsharma 

please response !!
i completed my task and design about page

check that and merge it

**Comment by dhruv8433** [comment]
@omrajsharma 

as your recommandation, i designed whole about page as you say
please merge it and if you want any kind of changes, inform me

it's your responsibility to check it and give response, i also solved all conflicts too...

**Comment by dhruv8433** [comment]
@omrajsharma 

i completed your task

as you said, i designed about page and resolve all errors and conflicts 
Screenshot 2024-05-14 at 16-39-48 BigOhhh - Code Your Dreams


please merge this pr

and kindly please inform me if you want any changes or facing any error to access that

**Comment by dhruv8433** [comment]
@Abh-I-seK 

can you please check this and merge it...

**Comment by dhruv8433** [comment]
@omrajsharma 

please add labels and merge it

**Comment by dhruv8433** [comment]
@omrajsharma 

please merge this and close #31

**Pull request closed without merging**
