### PR TITLE
BO#29: Expert Mentor Section

### LINKED ISSUE #29: [Enhancement]: Improve Expert Mentor Section
The mentor section has a very bad design 

Screenshot 2024-05-11 at 2 43 46 PM

### PR DESCRIPTION
**Pull request by 0xJaskeerat**
Fixes #29 

Updated mentor section 👇🏻

Screenshot 2024-05-13 at 10 12 07 AM

@omrajsharma Please review this PR

### CODE REVIEW

**Comment by omrajsharma** [comment]
@0xJaskeerat please resolve this conflict

**Comment by omrajsharma** [comment]
We've changed our project structure, you might need to take the latest pull of our repository then raise a PR. If you need any help you can let me know.

**Comment by 0xJaskeerat** [comment]
> We've changed our project structure, you might need to take the latest pull of our repository then raise a PR. If you need any help you can let me know.

@omrajsharma I have resolved all the conflicts, please review the PR and merge if this looks good to you as well

**Comment by omrajsharma** [comment]
Good work done brother @0xJaskeerat

**Comment by omrajsharma** [comment]
I'm merging the PR

**Pull request merged**
