### PR TITLE
Added The Pop-up Functionality on Subscribing Newsletter

### PR DESCRIPTION
**Pull request by prafulnigam**
Screenshot (477)

Kindly Merge The Changes. Thanks !

### CODE REVIEW

**Comment by omrajsharma** [comment]
I'm not been able to test this

**Comment by prafulnigam** [comment]
is there an error ?

**Comment by omrajsharma** [comment]
Yes I can see your change. You haven't put any validation on the form. Even empty input or non email input is showing the pop.

**Comment by prafulnigam** [comment]
i'll righ away fix that & make a new PR

**Comment by omrajsharma** [comment]
Can we make a global alerting utility for our application. This might extent this issue, but I'll create a new issue for it and you can work on it. After alerting utility, we can use that alerting in this PR and can merge both PRs.

**Comment by omrajsharma** [comment]
If you want then we can get on a call as well over discord.

**Comment by prafulnigam** [comment]
okay gotcha, let's fix up this PR & then we can proceed with the global alerting utility ( a new issue ). I'll need you to summarise the needed functionality as we'll connect over discord.

**Comment by omrajsharma** [comment]
Please DM me on discord.

**Comment by omrajsharma** [comment]
@prafulnigam any update ?

**Pull request closed without merging**
