### PR TITLE
About Page Added with New Route /about

### PR DESCRIPTION
**Pull request by dhruv8433**
added about page with new route about
 
added 
- hero section
- our story section
- instructors section
- news section
- investors section
- hiring partners section

output :
Screenshot 2024-05-13 at 12-29-13 BigOhhh - Code Your Dreams

### CODE REVIEW

**Comment by dhruv8433** [comment]
@omrajsharma  please check it and merge it

**Comment by omrajsharma** [comment]
Hi @dhruv8433 WE've updated our project's folder structure, you need to check it. Please take the latest pull of our project and then raise a new PR. if you need any help just DM me on discord.

**Comment by omrajsharma** [comment]
BTW good work done

**Comment by dhruv8433** [comment]
@omrajsharma 
Ok i will pull latest code and than create new pr

**Pull request closed without merging**
